### PR TITLE
[WIP] Fix icon installation location and fix permissions

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
:-(

**Comment by AsciiWolf** [comment]
I honestly have no idea what could be wrong and how to fix it. Everything looks fine, but the icon is not found by the buildbot check if not installed directly into `/app/share/app-info/icons/flatpak/` although there is `Exporting share/icons/hicolor/128x128/apps/in.srev.guiscrcpy.png` in the build log. @nedrichards @barthalion Any idea?

**Comment by barthalion** [comment]
https://github.com/srevinsaju/guiscrcpy/blob/main/appimage/guiscrcpy.appdata.xml#L13= This needs changing to app ID.

**Comment by AsciiWolf** [comment]
> https://github.com/srevinsaju/guiscrcpy/blob/main/appimage/guiscrcpy.appdata.xml#L13= This needs changing to app ID.

Hmm, interesting! I thought that this line is automatically replaced by flatpak-builder.

**Comment by AsciiWolf** [comment]
Everything seems to be fine now. @barthalion Thanks! :-)

**Comment by AsciiWolf** [comment]
guiscrcpy_fixed_gs

**Review by srevinsaju — APPROVED** [review]
Thanks a lot @AsciiWolf @barthalion !

**Pull request merged**
