### PR TITLE
Fix icon installation location

### PR DESCRIPTION
**Pull request by AsciiWolf**
The current one is not correct.

/cc @srevinsaju

### CODE REVIEW

**Comment by AsciiWolf** [comment]
I don't understand what is the problem here. Everything looks correct:

```
Exporting share/applications/in.srev.guiscrcpy.desktop
Not exporting share/icons/hicolor/256x256/apps/scrcpy.png, non-allowed export filename
Exporting share/icons/hicolor/256x256/apps/in.srev.guiscrcpy.png
Exporting share/icons/hicolor/128x128/apps/in.srev.guiscrcpy.png
Exporting share/appdata/in.srev.guiscrcpy.appdata.xml
```

Anyway, using the `/app/share/app-info/icons/flatpak/*` directory directly for icons installation is definitely not correct.

**Comment by AsciiWolf** [comment]
Hm, this is weird. It looks like some bug that you managed to workaround by installing the icons directly into `/app/share/app-info/icons/flatpak/*` (that is however not correct and causes the icon to be missing in AppStream metadata).

**Review by srevinsaju — APPROVED** [review]

**Comment by srevinsaju** [comment]
uh oh, merged it on mistake

**Comment by AsciiWolf** [comment]
Well, the PR I made seems to be technically correct and should be merged, but yeah, the bug should be fixed first. I will made a new PR and mark it as "WIP".

**Comment by AsciiWolf** [comment]
Well, the PR I made seems to be technically correct and should be merged, but yeah, the bug should be fixed first. I will make a new PR and mark it as "WIP".

**Pull request merged**
